### ISSUE TITLE
Error connecting to Java?

### ISSUE THREAD

**Issue by teamaonn** [jonese1234/PokeBotBad#18]
Continually getting this when i start the scripting for the bot. I'm sure it has something to do with Livesplits as Livesplits is not reading the bot's movements. Any ideas? 

For java, I currently have both the sdk and the normal versions, with the version being 8.131

**Comment by jonese1234** [comment]
Have you followed the set up guide exactly?

**Comment by teamaonn** [comment]
Is yours different from the versions that it's built off of?

**Comment by jonese1234** [comment]
Literally should not matter.

**Comment by teamaonn** [comment]
Then the answer is yes. I followed the install instructions.

**Comment by teamaonn** [comment]
Okay obviously did not see the instructions on your front page. My mistake. Got it now.
